-- Insert data for gender
INSERT INTO masterdata  (id, createdAt, updatedAt, `key`, value, category)
VALUES
(UUID(), NOW(), NOW(), 'M', 'Male', 'gender'),
(UUID(), NOW(), NOW(), 'F', 'Female', 'gender'),
(UUID(), NOW(), NOW(), 'O', 'Other', 'gender');

INSERT INTO masterdata  (id, createdAt, updatedAt, `key`, value, category)
VALUES
(UUID(), NOW(), NOW(), 'AF', 'Afghanistan', 'country'),
(UUID(), NOW(), NOW(), 'AL', 'Albania', 'country'),
(UUID(), NOW(), NOW(), 'DZ', 'Algeria', 'country'),
(UUID(), NOW(), NOW(), 'AS', 'American Samoa', 'country'),
(UUID(), NOW(), NOW(), 'AD', 'Andorra', 'country'),
(UUID(), NOW(), NOW(), 'AO', 'Angola', 'country'),
(UUID(), NOW(), NOW(), 'AI', 'Anguilla', 'country'),
(UUID(), NOW(), NOW(), 'AQ', 'Antarctica', 'country'),
(UUID(), NOW(), NOW(), 'AG', 'Antigua and Barbuda', 'country'),
(UUID(), NOW(), NOW(), 'AR', 'Argentina', 'country'),
(UUID(), NOW(), NOW(), 'AM', 'Armenia', 'country'),
(UUID(), NOW(), NOW(), 'AW', 'Aruba', 'country'),
(UUID(), NOW(), NOW(), 'AU', 'Australia', 'country'),
(UUID(), NOW(), NOW(), 'AT', 'Austria', 'country'),
(UUID(), NOW(), NOW(), 'AZ', 'Azerbaijan', 'country'),
(UUID(), NOW(), NOW(), 'BS', 'Bahamas', 'country'),
(UUID(), NOW(), NOW(), 'BH', 'Bahrain', 'country'),
(UUID(), NOW(), NOW(), 'BD', 'Bangladesh', 'country'),
(UUID(), NOW(), NOW(), 'BB', 'Barbados', 'country'),
(UUID(), NOW(), NOW(), 'BY', 'Belarus', 'country'),
(UUID(), NOW(), NOW(), 'BE', 'Belgium', 'country'),
(UUID(), NOW(), NOW(), 'BZ', 'Belize', 'country'),
(UUID(), NOW(), NOW(), 'BJ', 'Benin', 'country'),
(UUID(), NOW(), NOW(), 'BM', 'Bermuda', 'country'),
(UUID(), NOW(), NOW(), 'BT', 'Bhutan', 'country'),
(UUID(), NOW(), NOW(), 'BO', 'Bolivia', 'country'),
(UUID(), NOW(), NOW(), 'BA', 'Bosnia and Herzegovina', 'country'),
(UUID(), NOW(), NOW(), 'BW', 'Botswana', 'country'),
(UUID(), NOW(), NOW(), 'BR', 'Brazil', 'country'),
(UUID(), NOW(), NOW(), 'BN', 'Brunei', 'country'),
(UUID(), NOW(), NOW(), 'BG', 'Bulgaria', 'country'),
(UUID(), NOW(), NOW(), 'BF', 'Burkina Faso', 'country'),
(UUID(), NOW(), NOW(), 'BI', 'Burundi', 'country'),
(UUID(), NOW(), NOW(), 'KH', 'Cambodia', 'country'),
(UUID(), NOW(), NOW(), 'CM', 'Cameroon', 'country'),
(UUID(), NOW(), NOW(), 'CA', 'Canada', 'country'),
(UUID(), NOW(), NOW(), 'CV', 'Cape Verde', 'country'),
(UUID(), NOW(), NOW(), 'KY', 'Cayman Islands', 'country'),
(UUID(), NOW(), NOW(), 'CF', 'Central African Republic', 'country'),
(UUID(), NOW(), NOW(), 'TD', 'Chad', 'country'),
(UUID(), NOW(), NOW(), 'CL', 'Chile', 'country'),
(UUID(), NOW(), NOW(), 'CN', 'China', 'country'),
(UUID(), NOW(), NOW(), 'CO', 'Colombia', 'country'),
(UUID(), NOW(), NOW(), 'KM', 'Comoros', 'country'),
(UUID(), NOW(), NOW(), 'CG', 'Congo - Brazzaville', 'country'),
(UUID(), NOW(), NOW(), 'CD', 'Congo - Kinshasa', 'country'),
(UUID(), NOW(), NOW(), 'CR', 'Costa Rica', 'country'),
(UUID(), NOW(), NOW(), 'CI', 'Côte d’Ivoire', 'country'),
(UUID(), NOW(), NOW(), 'HR', 'Croatia', 'country'),
(UUID(), NOW(), NOW(), 'CU', 'Cuba', 'country'),
(UUID(), NOW(), NOW(), 'CY', 'Cyprus', 'country'),
(UUID(), NOW(), NOW(), 'CZ', 'Czechia', 'country'),
(UUID(), NOW(), NOW(), 'DK', 'Denmark', 'country'),
(UUID(), NOW(), NOW(), 'DJ', 'Djibouti', 'country'),
(UUID(), NOW(), NOW(), 'DM', 'Dominica', 'country'),
(UUID(), NOW(), NOW(), 'DO', 'Dominican Republic', 'country'),
(UUID(), NOW(), NOW(), 'EC', 'Ecuador', 'country'),
(UUID(), NOW(), NOW(), 'EG', 'Egypt', 'country'),
(UUID(), NOW(), NOW(), 'SV', 'El Salvador', 'country'),
(UUID(), NOW(), NOW(), 'GQ', 'Equatorial Guinea', 'country'),
(UUID(), NOW(), NOW(), 'ER', 'Eritrea', 'country'),
(UUID(), NOW(), NOW(), 'EE', 'Estonia', 'country'),
(UUID(), NOW(), NOW(), 'SZ', 'Eswatini', 'country'),
(UUID(), NOW(), NOW(), 'ET', 'Ethiopia', 'country'),
(UUID(), NOW(), NOW(), 'FJ', 'Fiji', 'country'),
(UUID(), NOW(), NOW(), 'FI', 'Finland', 'country'),
(UUID(), NOW(), NOW(), 'FR', 'France', 'country'),
(UUID(), NOW(), NOW(), 'GA', 'Gabon', 'country'),
(UUID(), NOW(), NOW(), 'GM', 'Gambia', 'country'),
(UUID(), NOW(), NOW(), 'GE', 'Georgia', 'country'),
(UUID(), NOW(), NOW(), 'DE', 'Germany', 'country'),
(UUID(), NOW(), NOW(), 'GH', 'Ghana', 'country'),
(UUID(), NOW(), NOW(), 'GR', 'Greece', 'country'),
(UUID(), NOW(), NOW(), 'GD', 'Grenada', 'country'),
(UUID(), NOW(), NOW(), 'GT', 'Guatemala', 'country'),
(UUID(), NOW(), NOW(), 'GN', 'Guinea', 'country'),
(UUID(), NOW(), NOW(), 'GW', 'Guinea-Bissau', 'country'),
(UUID(), NOW(), NOW(), 'GY', 'Guyana', 'country'),
(UUID(), NOW(), NOW(), 'HT', 'Haiti', 'country'),
(UUID(), NOW(), NOW(), 'HN', 'Honduras', 'country'),
(UUID(), NOW(), NOW(), 'HK', 'Hong Kong', 'country'),
(UUID(), NOW(), NOW(), 'HU', 'Hungary', 'country'),
(UUID(), NOW(), NOW(), 'IS', 'Iceland', 'country'),
(UUID(), NOW(), NOW(), 'IN', 'India', 'country'),
(UUID(), NOW(), NOW(), 'ID', 'Indonesia', 'country'),
(UUID(), NOW(), NOW(), 'IR', 'Iran', 'country'),
(UUID(), NOW(), NOW(), 'IQ', 'Iraq', 'country'),
(UUID(), NOW(), NOW(), 'IE', 'Ireland', 'country'),
(UUID(), NOW(), NOW(), 'IL', 'Israel', 'country'),
(UUID(), NOW(), NOW(), 'IT', 'Italy', 'country'),
(UUID(), NOW(), NOW(), 'JM', 'Jamaica', 'country'),
(UUID(), NOW(), NOW(), 'JP', 'Japan', 'country'),
(UUID(), NOW(), NOW(), 'JO', 'Jordan', 'country'),
(UUID(), NOW(), NOW(), 'KZ', 'Kazakhstan', 'country'),
(UUID(), NOW(), NOW(), 'KE', 'Kenya', 'country'),
(UUID(), NOW(), NOW(), 'KI', 'Kiribati', 'country'),
(UUID(), NOW(), NOW(), 'KP', 'North Korea', 'country'),
(UUID(), NOW(), NOW(), 'KR', 'South Korea', 'country'),
(UUID(), NOW(), NOW(), 'KW', 'Kuwait', 'country'),
(UUID(), NOW(), NOW(), 'KG', 'Kyrgyzstan', 'country'),
(UUID(), NOW(), NOW(), 'LA', 'Laos', 'country'),
(UUID(), NOW(), NOW(), 'LV', 'Latvia', 'country'),
(UUID(), NOW(), NOW(), 'LB', 'Lebanon', 'country'),
(UUID(), NOW(), NOW(), 'LS', 'Lesotho', 'country'),
(UUID(), NOW(), NOW(), 'LR', 'Liberia', 'country'),
(UUID(), NOW(), NOW(), 'LY', 'Libya', 'country'),
(UUID(), NOW(), NOW(), 'LI', 'Liechtenstein', 'country'),
(UUID(), NOW(), NOW(), 'LT', 'Lithuania', 'country'),
(UUID(), NOW(), NOW(), 'LU', 'Luxembourg', 'country'),
(UUID(), NOW(), NOW(), 'MG', 'Madagascar', 'country'),
(UUID(), NOW(), NOW(), 'MW', 'Malawi', 'country'),
(UUID(), NOW(), NOW(), 'MY', 'Malaysia', 'country'),
(UUID(), NOW(), NOW(), 'MV', 'Maldives', 'country'),
(UUID(), NOW(), NOW(), 'ML', 'Mali', 'country'),
(UUID(), NOW(), NOW(), 'MT', 'Malta', 'country'),
(UUID(), NOW(), NOW(), 'MH', 'Marshall Islands', 'country'),
(UUID(), NOW(), NOW(), 'MR', 'Mauritania', 'country'),
(UUID(), NOW(), NOW(), 'MU', 'Mauritius', 'country'),
(UUID(), NOW(), NOW(), 'MX', 'Mexico', 'country'),
(UUID(), NOW(), NOW(), 'FM', 'Micronesia', 'country'),
(UUID(), NOW(), NOW(), 'MD', 'Moldova', 'country'),
(UUID(), NOW(), NOW(), 'MC', 'Monaco', 'country'),
(UUID(), NOW(), NOW(), 'MN', 'Mongolia', 'country'),
(UUID(), NOW(), NOW(), 'ME', 'Montenegro', 'country'),
(UUID(), NOW(), NOW(), 'MA', 'Morocco', 'country'),
(UUID(), NOW(), NOW(), 'MZ', 'Mozambique', 'country'),
(UUID(), NOW(), NOW(), 'MM', 'Myanmar (Burma)', 'country'),
(UUID(), NOW(), NOW(), 'NA', 'Namibia', 'country'),
(UUID(), NOW(), NOW(), 'NR', 'Nauru', 'country'),
(UUID(), NOW(), NOW(), 'NP', 'Nepal', 'country'),
(UUID(), NOW(), NOW(), 'NL', 'Netherlands', 'country'),
(UUID(), NOW(), NOW(), 'NZ', 'New Zealand', 'country'),
(UUID(), NOW(), NOW(), 'NI', 'Nicaragua', 'country'),
(UUID(), NOW(), NOW(), 'NE', 'Niger', 'country'),
(UUID(), NOW(), NOW(), 'NG', 'Nigeria', 'country'),
(UUID(), NOW(), NOW(), 'NO', 'Norway', 'country'),
(UUID(), NOW(), NOW(), 'OM', 'Oman', 'country'),
(UUID(), NOW(), NOW(), 'PK', 'Pakistan', 'country'),
(UUID(), NOW(), NOW(), 'PW', 'Palau', 'country'),
(UUID(), NOW(), NOW(), 'PS', 'Palestine', 'country'),
(UUID(), NOW(), NOW(), 'PA', 'Panama', 'country'),
(UUID(), NOW(), NOW(), 'PG', 'Papua New Guinea', 'country'),
(UUID(), NOW(), NOW(), 'PY', 'Paraguay', 'country'),
(UUID(), NOW(), NOW(), 'PE', 'Peru', 'country'),
(UUID(), NOW(), NOW(), 'PH', 'Philippines', 'country'),
(UUID(), NOW(), NOW(), 'PL', 'Poland', 'country'),
(UUID(), NOW(), NOW(), 'PT', 'Portugal', 'country'),
(UUID(), NOW(), NOW(), 'QA', 'Qatar', 'country'),
(UUID(), NOW(), NOW(), 'RO', 'Romania', 'country'),
(UUID(), NOW(), NOW(), 'RU', 'Russia', 'country'),
(UUID(), NOW(), NOW(), 'RW', 'Rwanda', 'country'),
(UUID(), NOW(), NOW(), 'WS', 'Samoa', 'country'),
(UUID(), NOW(), NOW(), 'SM', 'San Marino', 'country'),
(UUID(), NOW(), NOW(), 'ST', 'São Tomé and Príncipe', 'country'),
(UUID(), NOW(), NOW(), 'SA', 'Saudi Arabia', 'country'),
(UUID(), NOW(), NOW(), 'SN', 'Senegal', 'country'),
(UUID(), NOW(), NOW(), 'RS', 'Serbia', 'country'),
(UUID(), NOW(), NOW(), 'SC', 'Seychelles', 'country'),
(UUID(), NOW(), NOW(), 'SL', 'Sierra Leone', 'country'),
(UUID(), NOW(), NOW(), 'SG', 'Singapore', 'country'),
(UUID(), NOW(), NOW(), 'SK', 'Slovakia', 'country'),
(UUID(), NOW(), NOW(), 'SI', 'Slovenia', 'country'),
(UUID(), NOW(), NOW(), 'SB', 'Solomon Islands', 'country'),
(UUID(), NOW(), NOW(), 'SO', 'Somalia', 'country'),
(UUID(), NOW(), NOW(), 'ZA', 'South Africa', 'country'),
(UUID(), NOW(), NOW(), 'ES', 'Spain', 'country'),
(UUID(), NOW(), NOW(), 'LK', 'Sri Lanka', 'country'),
(UUID(), NOW(), NOW(), 'SD', 'Sudan', 'country'),
(UUID(), NOW(), NOW(), 'SR', 'Suriname', 'country'),
(UUID(), NOW(), NOW(), 'SE', 'Sweden', 'country'),
(UUID(), NOW(), NOW(), 'CH', 'Switzerland', 'country'),
(UUID(), NOW(), NOW(), 'SY', 'Syria', 'country'),
(UUID(), NOW(), NOW(), 'TW', 'Taiwan', 'country'),
(UUID(), NOW(), NOW(), 'TJ', 'Tajikistan', 'country'),
(UUID(), NOW(), NOW(), 'TZ', 'Tanzania', 'country'),
(UUID(), NOW(), NOW(), 'TH', 'Thailand', 'country'),
(UUID(), NOW(), NOW(), 'TL', 'Timor-Leste', 'country'),
(UUID(), NOW(), NOW(), 'TG', 'Togo', 'country'),
(UUID(), NOW(), NOW(), 'TO', 'Tonga', 'country'),
(UUID(), NOW(), NOW(), 'TT', 'Trinidad and Tobago', 'country'),
(UUID(), NOW(), NOW(), 'TN', 'Tunisia', 'country'),
(UUID(), NOW(), NOW(), 'TR', 'Turkey', 'country'),
(UUID(), NOW(), NOW(), 'TM', 'Turkmenistan', 'country'),
(UUID(), NOW(), NOW(), 'TV', 'Tuvalu', 'country'),
(UUID(), NOW(), NOW(), 'UG', 'Uganda', 'country'),
(UUID(), NOW(), NOW(), 'UA', 'Ukraine', 'country'),
(UUID(), NOW(), NOW(), 'AE', 'United Arab Emirates', 'country'),
(UUID(), NOW(), NOW(), 'GB', 'United Kingdom', 'country'),
(UUID(), NOW(), NOW(), 'US', 'United States', 'country'),
(UUID(), NOW(), NOW(), 'UY', 'Uruguay', 'country'),
(UUID(), NOW(), NOW(), 'UZ', 'Uzbekistan', 'country'),
(UUID(), NOW(), NOW(), 'VU', 'Vanuatu', 'country'),
(UUID(), NOW(), NOW(), 'VE', 'Venezuela', 'country'),
(UUID(), NOW(), NOW(), 'VN', 'Vietnam', 'country'),
(UUID(), NOW(), NOW(), 'YE', 'Yemen', 'country'),
(UUID(), NOW(), NOW(), 'ZM', 'Zambia', 'country'),
(UUID(), NOW(), NOW(), 'ZW', 'Zimbabwe', 'country');